name: Deploy Angular App to Static Web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Configure .npmrc for Artifactory
        run: |
          echo "//ARTIFACT_DOMAIN/api/npm/genesis-npm-dev/:_auth=${{ secrets.ARTIFACTORY_AUTH_TOKEN }}" > .npmrc
          echo "always-auth=true" >> .npmrc
          echo "email=youremail@email.com" >> .npmrc
          echo "registry=https://devopstdp.eastus2.cloudapp.azure.com/artifactory/api/npm/genesis-npm-dev/" >> .npmrc

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install dependencies without cache
        run: npm install --prefer-online --fetch-retries=3 --fetch-timeout=60000

      - name: Verify .npmrc configuration
        run: cat .npmrc

      - name: Build Angular app
        run: npm run build --prod

      - name: Deploy to Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          app_location: "/"
          output_location: "dist/st-web-app"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
